### ISSUE TITLE
unable to access http://webaim.org/standards/wcag/checklist

### ISSUE THREAD

**Issue by noahehall** [udacity/ud891#11]
with such a heavy focus on the checklist, is it possible to make a summary avaiable directly in the udacity course?

**Comment by robdodson** [comment]
Hi @noahehall,

I'd rather folks use the canonical checklist mainly because we don't have a system for keeping track of any edits they might make to it. Are you still unable to access the checklist at the address linked above?

**Comment by noahehall** [comment]
Yes its working now, yesterday was returning 500
