### ISSUE TITLE
Unable to solve quiz with text editor (Lesson 3 - 05)

### ISSUE THREAD

**Issue by davidatthepark** [udacity/ud891#15]
I have been solving the quizzes through a fork but stumbled a bit while working on lesson3-semantics-built-in/05-writing-semantic-html. When I changed the div to a button, I expected to see the secret word after a page refresh. This didn't work and I realized later (after watching the solution and seeing the JS code) that I could only solve the problem by mutating the element through the console. 

I think it would be nice for users to have the option of solving the problem with their own text editors. Any thoughts on this?

**Comment by robdodson** [comment]
@alice

**Comment by daphnedeng** [comment]
same issue here.

**Comment by cpcamp2** [comment]
It's "MARSUPIAL"

**Comment by devbdavis** [comment]
The issue on this one is that they want you to edit the element in your browser for some reason? Not sure why it was only set up as a mutation observer.

A fix for this would be to show the secret word on page load if the div is missing and the button is present. ex:

```javascript
function checkForFix() {
  var main = document.querySelector('main');
  var div = main.querySelector('div#wombats-button');
  var button = main.querySelector('button#wombats-button');
  if(!div && button) {
    document.querySelector('.secret').textContent = 'The secret word is: "MARSUPIAL"'
    document.querySelector('header').classList.add('success');
  }
}
checkForFix();
```
