### ISSUE TITLE
"entry not found" in Lesson 2 Exercise 3

### ISSUE THREAD

**Issue by dgreene1** [udacity/ud891#16]
If you click on a tab in this exercise, you accidentally get taken to a new page with the content of "entry not found." lesson2-focus/03-managing-focus/index.html#!/lesson2-focus/03-managing-focus/index.html

I believe the issue might be the result of a bad merge or something where the file that corresponds with the tab link is now missing:

![image](https://cloud.githubusercontent.com/assets/14020024/24965315/b1436da6-1f71-11e7-8260-20a45ce14626.png)

**Comment by robdodson** [comment]
oh dear, yeah this example is totally broken. Thanks for bringing it up

**Comment by robdodson** [comment]
oh I see the problem!

Sorry, you should be running your _server_ from the `lesson2-focus/03-managing-focus` directory.

Note in the screen shot where it says 'Choose Folder'. I'll update the repo to make this more clear.

![image](https://cloud.githubusercontent.com/assets/1066253/25058019/470977ae-212a-11e7-842a-fd5475e0decc.png)

**Comment by richard-hijzen** [comment]
Also here it doesn't work as i expected https://htmlpreview.github.io/?https://github.com/udacity/ud891/blob/gh-pages/lesson2-focus/03-managing-focus/solution/index.html

**Comment by robdodson** [comment]
I believe it's because the URL isn't expecting to live within a nested folder structure. You need to run a local server so the 03-managing-focus directory is the root.

For what it's worth I plan to update these samples in the near future to remove this issue.
