### ISSUE TITLE
Accessibility, stealing focus

### ISSUE THREAD

**Issue by teddymro** [udacity/ud891#18]
04-offscreen-content

Chrome Audis tab has Lighthouse and Accessibility test finds no issue

![image](https://user-images.githubusercontent.com/3188248/31716599-4f99c296-b411-11e7-8268-542689fd7f9b.png)

**Comment by robdodson** [comment]
This is one of those things that is really difficult for an automated testing tool to actually test. As a result, there's a lot of things that Lighthouse doesn't cover.

We're planning to update the language in the audits panel to match similar language used by accessibility testing tools like aXe:

> Please note that only 20% to 50% of all accessibility issues can automatically be detected.
> Manual testing is always required. For more information see:
> https://dequeuniversity.com/curriculum/courses/archive/1.0/testing
