### ISSUE TITLE
Lesson 2 - Focus - Quiz.

### ISSUE THREAD

**Issue by furzeface** [udacity/ud891#2]
Hello,

In the quiz instructions it asks to enter 
- _leaving on 10/12/2017_
- _returning on 10/23/2017_

it's just a slight bit misleading as the date inputs in the form are _dd/mm/yyyy_ - it frustrated me for a few minutes!

Thanks! :octocat:

**Comment by robdodson** [comment]
Darn, yeah I think the date format is determined by the user's machine calendar. I'll add an instructor note.
