### ISSUE TITLE
opening with atom or brackets

### ISSUE THREAD

**Issue by sbontheroad** [udacity/ud891#20]
Hi, thanks for posting this course.  I'm a new developer and I'm trying to do your exercises.  I was unable to get the javascript to work using web server for chrome and editing via inspect (even though I did change both the html and main.js files), so I forked the code and downloaded it to use in atom or brackets. When launching in atom or brackets I can't get the main content to show. I only see the header and navbar.  Selecting items in the navbar also do not show the main content.  Can you give me any guidance?  I was trying to do 03-managing-focus.  Thank you!

**Comment by robdodson** [comment]
It may depend from which directory you run your local server. If you open the console in the browser do you see any errors like 404s?

**Comment by anushikab** [comment]
Please advice on this issue I am having the same problem @robdodson

**Comment by robdodson** [comment]
Hey @anushikab, are you also doing the 03-managing-focus exercise? If so, you'll need to start a local development server and have it host the 03-managing-focus directory. There are some instructions here: https://github.com/udacity/ud891/tree/gh-pages/lesson2-focus/03-managing-focus

**Comment by FerrusDude** [comment]
Hi @robdodson, I am hosting the udacity tutorial content on a local nginx host.
When I attempt this task, __03-managing-focus__, click actions on the navigation links produce an actual navigation and the following error _The requested URL /lesson2-focus/03-managing-focus/recipes was not found on this server._ The expected result is of course for the content to load into the main area. Could this be an issue with `page.js`?

**Comment by robdodson** [comment]
You'll need to run the server so the root is at `/03-managing-focus`. It looks like you're running it so the root is the repo itself.
