### ISSUE TITLE
The intro is missing for Lesson 2 Exercise 14

### ISSUE THREAD

**Issue by anton-github** [udacity/ud891#21]
Hi and thanks for your awesome course!

It seems like something wrong with intro for Lesson 2 Exercise 14 (Implementing Keyboard Event Listeners), it shows just 3 seconds of static picture

**Comment by robdodson** [comment]
Yeah I think the video where Michael explains this bit may have gone missing unfortunately. There is an explanation below the video which describes what to do.

**Comment by hbkwong** [comment]
Just to close the loop on this one: the exercise has since been revamped completely!
