### ISSUE TITLE
Possibly missing click handlers, activation of the page router

### ISSUE THREAD

**Issue by FerrusDude** [udacity/ud891#23]
Please add the following code to activate the router at line 27.

```javascript
page.start();
```

https://github.com/udacity/ud891/blob/3a13521392da95ebc97b6d759e39e6caf3a22c62/lesson2-focus/03-managing-focus/scripts/main.js#L26
Possibly related to #20 

There seem to be missing click handlers that connect the links to `page`.
https://github.com/udacity/ud891/blob/3a13521392da95ebc97b6d759e39e6caf3a22c62/lesson2-focus/03-managing-focus/index.html#L39-L41

**Comment by robdodson** [comment]
I don't think anything needs to be added. I just tested it and everything seemed to work fine. The router intercepts clicks on anchor elements so you don't need to add additional click handlers. If you run the server so the root is at 03-managing-focus, does it still not work for you?

**Comment by FerrusDude** [comment]
I will have to try it with a more specific root. Thanks, @robdodson !
