### ISSUE TITLE
Lesson 3.12

### ISSUE THREAD

**Issue by emily-kay** [udacity/ud891#56]
The code for the live site appears to be different from the current repository. When I change the div to a button on the live site, text appears at the top with the secret word. When I do the same thing for the code I forked and cloned today, a picture appears in the background of a wombat but no secret text is visible.

**Comment by robdodson** [comment]
Hey @emily-kay I bet that might happen if the local server isn't being run in the right directory. If you open the console in Chrome for your local version you might see errors related to chromevox-lite.

Can you try running a server from the root of the cloned project and then do the test again. I just tried and it seemed to work.

I may look into moving all of these examples to Glitch so folks don't have to mess with the local server step.
