### ISSUE TITLE
...lesson6-styling/02-style-aria-states/solution/main-solution.css net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by ghost** [udacity/ud891#63]
It should be `<link rel="stylesheet" href="main.css">`.

![image](https://user-images.githubusercontent.com/25172271/53747479-1cb7f800-3e82-11e9-9c09-99fafa7f6d35.png)

[ud891/lesson6-styling/02-style-aria-states/solution/index.html](https://github.com/udacity/ud891/blob/gh-pages/lesson6-styling/02-style-aria-states/solution/index.html) **line 8**

**Comment by robdodson** [comment]
updated thanks :)
