### ISSUE TITLE
Incorrect Expected Answer for Quiz: Experience a Screen Reader

### ISSUE THREAD

**Issue by ghost** [udacity/ud891#7]
In Quiz: Experience a Screen Reader, the screen reader clearly states the role of the form element as "Edit text, email entry".  However this is marked incorrect, as the expected answer is "Edit text".

**Comment by robdodson** [comment]
ah sorry if this is not more clear. Screen readers typically read both the role and the name together. So the role is `Edit text` and the name is `email entry`.
